title:            Christophe Hamerling
description:      Christophe Hamerling Lines of Code.
url:              # Site url.

# Owner/author information
owner:
  name:           C. Hamerling
  avatar:         chamerling.png
  bio:            "Software Hacker, Creating the @AwesomePaaS Enterprise Social Network and playing with drones @linagora"
  email:          chamerling@linagora.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: chamerling
  facebook:
  github: chamerling
  stackoverflow:
  linkedin: chamerling
  instagram: chamerling
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:


links:
  - title:        About
    url:          /about
  - title:        Posts
    url:          http://github.com/chamerling/articles
    external:     true
  - title:        Contact
    url:          mailto:chamerling@linagora.com
    external:     true
  - title:        Slides
    url:          http://chamerling.github.io/slides/content
    external:     true
    
highlighter:      true
permalink:        pretty
markdown:         kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class