title:            Christophe Hamerling
description:      Christophe Hamerling Lines of Code.
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Articles
    url:          /articles
  - name:         Email
    url:          mailto:christophe.hamerling@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/chamerling
    external:     true
  - name:         Slides
    url:          http://chamerling.github.io/slides/content
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]